spring.application.name=LiveShield

server.port=${PORT:8081}

# ============================================================
# DATABASE
# ============================================================

spring.datasource.url=jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

# ============================================================
# THYMELEAF
# ============================================================

spring.thymeleaf.cache=false

# ============================================================
# ACTUATOR
# ============================================================

management.endpoints.web.exposure.include=health,info

# ============================================================
# EMAIL NOTIFICATIONS
# ============================================================



liveshield.admin.emails=${ADMIN_EMAILS}

# ============================================================
# WHATSAPP NOTIFICATIONS - TWILIO
# ============================================================

twilio.account-sid=${TWILIO_ACCOUNT_SID}
twilio.auth-token=${TWILIO_AUTH_TOKEN}
twilio.whatsapp-from=${TWILIO_WHATSAPP_FROM}

liveshield.admin.whatsapp-numbers=${LIVESHIELD_ADMIN_WHATSAPP_NUMBERS}


google.gmail.client-id=${GOOGLE_GMAIL_CLIENT_ID}
google.gmail.client-secret=${GOOGLE_GMAIL_CLIENT_SECRET}
google.gmail.refresh-token=${GOOGLE_GMAIL_REFRESH_TOKEN}
google.gmail.sender-email=${GOOGLE_GMAIL_SENDER_EMAIL}


